- import_playbook: generate_key.yml
- import_playbook: conf_user.yml
- import_playbook: httpd_install.yml
- import_playbook: java_install.yml

- hosts: appservers
  tags:
  - sanity
  tasks:
  - include_role:
      name: tests
      tasks_from: jenkins
    vars:
      procname: java
      username: jenkins

- hosts: webservers
  tags:
  - sanity
  tasks:
  - include_role:
      name: tests
      tasks_from: httpd
    vars:
      process: httpd



- hosts: local
  tasks:
  - name: final msg
    debug:
      msg: "Finally success"
    tags: always

  - name: never msg
    debug:
      msg: "Run with never tag"
    tags: never

