- name: Generate key
  hosts: local
  pre_tasks:
  - name: Create fact folder
    become: yes
    file:
      path: /etc/ansible/facts.d
      state: directory
  tasks:
  roles: 
  - common
  post_tasks:
  - debug:
      msg: "{{ ansible_local }}"     

- name: Configuring devops user
  hosts: nodes
  pre_tasks:
  - name: Create fact folder
    become: yes
    file:
      path: /etc/ansible/facts.d
      state: directory
  roles:
  - devops_user

- name: Install httpd
  hosts: webservers
  roles:
  - httpd
  post_tasks:
  - debug:
      msg: "{{ ansible_local }}"     

- name: Install Java & Jenkins
  vars: 
  - jenkins_version: 2.121.2
  hosts: appservers
  roles:
  - jenkins
  post_tasks:
  - debug:
      msg: "{{ ansible_local }}"     
