- name: Ensure group exists
  become: yes
  group:
    name: "{{ user_group }}"
    state: present
- name: user create
  become: yes
  user:
    name: "{{ user_name }}"
    group: "{{ user_group }}"
    create_home: True
- name: Allow specified groups to sudo
  become: yes
  template:
    src: sudoers.j2
    dest: '/etc/sudoers.d/{{ user_name }}'
- name: copy key
  become: yes
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', '~/ansible/day2/devops.pub') }}"
- name: Create fact folder
  become: yes
  file:
    path: /etc/ansible/facts.d
    state: directory
- name: Get version
  shell: id -u devops 2>&1
  register: user_id
  changed_when: no
- name: Save fact
  become: yes
  copy:
    content:
      {
        "User": "{{ user_name }}", "User ID": "{{ user_id.stdout }}", "User group": "{{ user_group }}"
      }
    dest: /etc/ansible/facts.d/user.fact

