- block:
  - name: Create java_home
    become: yes
    file:
      path: "/opt/oracle/java/{{java_version}}"
      state: directory
      recurse: yes
  - name: Copy java packaje
    become: yes
    copy:
      src: "{{ packages[java_version] }}"
      dest: /opt/oracle/java/{{ java_version }}/  
  - name: Save fact
    become: yes
    copy:
      content:
        {
          "version": "{{ java_version }}"
        }
      dest: /etc/ansible/facts.d/java.fact
  when:
    - ansible_local.java.version != java_version
