- name: Install java package
  become: yes
  yum:
    name: java-1.{{ jre_open_jdk_version }}.0
    state: present
- name: Get version
  shell: /usr/bin/java -version 2>&1|grep version|awk '{print $3}'| sed 's/"//g'
  register: java_version
  changed_when: no
- name: Save fact
  become: yes
  copy:
    content:
      {
        "version": "{{ java_version.stdout }}"
      }
    dest: /etc/ansible/facts.d/java.fact

