- name: Ensure group exists
  become: yes
  group:
    name: "{{ user_group }}"
    gid: "{{ user_group_id }}"
    state: present
- name: user create
  become: yes
  user:
    name: "{{ user_name }}"
    group: "{{ user_group }}"
    uid: "{{ user_id }}"
    create_home: True
- name: Ensure Jenkins repo is installed.
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo
  when: jenkins_repo_url != ''
- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "{{ jenkins_repo_key_url }}"
- name: Download specific Jenkins version.   
  become: yes
  get_url:      
    url: "{{ jenkins_pkg_url }}/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    dest: "/home/{{ user_name }}/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
- name: Ensure Jenkins is installed.
  become: yes
  package:
    name: /home/{{ user_name }}/jenkins-{{ jenkins_version }}-1.1.noarch.rpm
    state: present
- name: Ensure Jenkins is started and runs on startup.
  become: yes 
  environment:
    JAVA_OPTS: "{{ java_opts }}"
  service:
    name: jenkins
    state: started
    enabled: yes
- name: Wait until Jenkins starts
  become: yes
  wait_for:
    path: /var/log/jenkins/jenkins.log
    search_regex: "Jenkins is fully up and running"
- name: Create fact folder
  become: yes
  file:
    path: /etc/ansible/facts.d
    state: directory
- name: Get version
  shell: java -jar /usr/lib/jenkins/jenkins.war --version
  register: jenkins_version
  changed_when: no
- name: Save fact
  become: yes
  copy:
    content:
      {
        "version": "{{ jenkins_version.stdout }}"
      }
    dest: /etc/ansible/facts.d/jenkins.fact

