user_name: jenkins
user_group: jenkins
jenkins_repo_url: https://pkg.jenkins.io/redhat/jenkins.repo
jenkins_repo_key_url: https://pkg.jenkins.io/redhat/jenkins.io.key
jenkins_pkg_url: https://pkg.jenkins.io/redhat

